### PR TITLE
Prepare package for Atom 1.0

### PR DESCRIPTION
**Pull request by jasonrudolph**
Prior to this pull request, Atom reports the following deprecations for the maximize-panes package:

screen shot 2015-05-20 at 9 02 20 am
screen shot 2015-05-20 at 9 02 28 am

This pull request resolves all of those deprecations.

### CODE REVIEW

**Comment by DominicBarnard** [comment]
:+1:

**Comment by petemill** [comment]
@santip will you merge and release the update, or give someone else write access to this repo? Otherwise we will have to fork and deploy a clone of this in to apm :-1:

**Comment by santip** [comment]
done released as 0.2.0

thanks

**Comment by jasonrudolph** [comment]
Thanks, @santip! :bow:

**Pull request merged**
